# Generated by Claude Sonnet 4.6

from __future__ import annotations

import argparse
import json
import numpy as np
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from metrics import cdd_gender, cdd_language
from read_data import ROLES, log, read_scalar_annotation


# --- Official MultiMediate'26 scoring, replicated from hcmlab/MultiMediate26 baseline/5_CreateResulttable.py ---
def load_csv(path: Path) -> np.ndarray:
    """Official reader: one value per line; empty and 'nan' / '-nan(ind)' lines are DROPPED
    (not interpolated), unparsable lines become NaN and are masked out later."""
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        text = path.read_bytes().decode("latin-1", errors="ignore")
    vals = []
    for ln in (l.strip() for l in text.splitlines()):
        if not ln or ln.lower() in ("nan", "-nan(ind)"):
            continue
        try:
            vals.append(float(ln))
        except ValueError:
            vals.append(float("nan"))
    return np.asarray(vals, dtype=np.float32)


def official_ccc(x: np.ndarray, y: np.ndarray) -> float:
    """Official CCC: population variance, no epsilon."""
    vx, vy = np.var(x), np.var(y)
    s_xy = np.mean((x - np.mean(x)) * (y - np.mean(y)))
    denom = vx + vy + (np.mean(x) - np.mean(y)) ** 2
    return float("nan") if denom == 0.0 else float((2 * s_xy) / denom)


def find_pred(pred_session: Path, role: str) -> Path:
    """Official name is {role}.engagement.pred.csv; fall back to our older .annotation.csv outputs."""
    p = pred_session / f"{role}.engagement.pred.csv"
    return p if p.exists() else pred_session / f"{role}.engagement.annotation.csv"


def read_gender_raw(session_dir: Path, role: str) -> str:
    p = session_dir / f"{role}.gender.annotation.csv"
    return read_scalar_annotation(p).strip().lower() if p.exists() else ""


def build_gender_map(raw_codes: set[str]) -> dict[str, int]:
    named = {"female": 0, "male": 1, "f": 0, "m": 1}
    present = {c for c in raw_codes if c}
    if present and present <= set(named):
        return {c: named[c] for c in present}

    ordered = sorted(present)
    if len(ordered) != 2:
        return {}
    return {ordered[0]: 0, ordered[1]: 1}


def read_language(session_dir: Path) -> str:
    p = session_dir / "language.annotation.csv"
    return read_scalar_annotation(p).strip() if p.exists() else "unknown"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--submission-dir", type=str, required=True)
    parser.add_argument("--data-root", type=str, required=True)
    parser.add_argument("--corpora", nargs="+", default=["NoXi", "NoXi+J"])
    parser.add_argument("--split", type=str, default="val")
    args = parser.parse_args()

    submission_dir = Path(args.submission_dir)
    data_root = Path(args.data_root)

    per_domain_cccs: dict[str, float] = {}
    per_domain_cdd_g: dict[str, float] = {}
    per_domain_cdd_l: dict[str, dict[str, float]] = {}

    for corpus in args.corpora:
        gt_dir = data_root / corpus / args.split
        pred_dir = submission_dir / corpus / args.split

        if not gt_dir.exists():
            log.info(f"Skipping {corpus}/{args.split} (ground-truth not found)")
            continue
        if not pred_dir.exists():
            log.info(f"Skipping {corpus}/{args.split} (predictions not found)")
            continue

        all_preds = []
        all_targets = []
        all_genders = []
        all_languages = []

        session_dirs = sorted([p for p in gt_dir.iterdir() if p.is_dir()])

        for session_dir in session_dirs:
            pred_session = pred_dir / session_dir.name
            language = read_language(session_dir)

            for role in ROLES:
                gt_path = session_dir / f"{role}.engagement.annotation.csv"
                pred_path = find_pred(pred_session, role)

                if not gt_path.exists() or not pred_path.exists():
                    continue

                gt = load_csv(gt_path)
                pred = load_csv(pred_path)

                min_len = min(len(gt), len(pred))
                pred, gt = pred[:min_len], gt[:min_len]
                mask = np.isfinite(pred) & np.isfinite(gt)
                if not mask.any():
                    continue
                pred, gt = pred[mask], gt[mask]
                n = len(pred)
                all_preds.append(pred)
                all_targets.append(gt)
                # Gender is per participant, language per session - broadcast to per-frame
                all_genders.append(np.full(n, read_gender_raw(session_dir, role), dtype=object))
                all_languages.append(np.full(n, language, dtype=object))

        if not all_preds:
            log.info(f"{corpus}/{args.split}: no valid sessions")
            continue

        corpus_preds = np.concatenate(all_preds)
        corpus_targets = np.concatenate(all_targets)
        corpus_ccc = official_ccc(corpus_preds, corpus_targets)
        per_domain_cccs[corpus] = corpus_ccc
        log.info(f"{corpus}/{args.split}: CCC = {corpus_ccc:.4f} ({len(session_dirs)} sessions, {len(corpus_preds)} frames)")

        # CDD_G - prediction bias between genders, matched within target-value bins.
        raw_genders = np.concatenate(all_genders)
        gmap = build_gender_map(set(raw_genders.tolist()))
        if gmap:
            genders = np.array([gmap.get(c, -1) for c in raw_genders], dtype=np.int8)
            known = genders >= 0
            g = cdd_gender(corpus_preds[known], corpus_targets[known], genders[known])
            per_domain_cdd_g[corpus] = g
            log.info(f"{corpus}/{args.split}: CDD_G = {g:+.4f} using code map {gmap} ({int(known.sum())} frames) - magnitude is meaningful, sign depends on which id is male (needs NoXi_MetaData.xlsx)")
        else:
            log.warning(f"{corpus}/{args.split}: CDD_G skipped - need exactly two gender codes, found {sorted(set(raw_genders.tolist()))}")

        # CDD_L - per-language deviation from the overall prediction, within the same bins.
        languages = np.concatenate(all_languages)
        if len(np.unique(languages)) > 1:
            l = cdd_language(corpus_preds, corpus_targets, languages)
            per_domain_cdd_l[corpus] = l
            log.info(f"{corpus}/{args.split}: CDD_L = " + ", ".join(f"{k}={v:.4f}" for k, v in sorted(l.items())))
        else:
            log.warning(f"{corpus}/{args.split}: CDD_L skipped - only one language present ({np.unique(languages).tolist()})")

    # Official combined = plain mean over the datasets present (finite values only)
    finite = [v for v in per_domain_cccs.values() if np.isfinite(v)]
    c_ccc = float(np.mean(finite)) if finite else None
    if c_ccc is not None:
        log.info(f"Combined CCC: {c_ccc:.4f}")

    results = {
        "per_domain_ccc": per_domain_cccs,
        "combined_ccc": c_ccc,
        "per_domain_cdd_gender": per_domain_cdd_g,
        "per_domain_cdd_language": per_domain_cdd_l,
    }
    out_path = submission_dir / "results.json"
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    log.info(f"Results saved to {out_path}")


if __name__ == "__main__":
    main()
